SELECT * FROM ANIMAL_INS ORDER BY ANIMAL_ID;   # Q1

SELECT NAME, DATETIME FROM ANIMAL_INS 
ORDER BY ANIMAL_ID DESC;    # Q2


SELECT ANIMAL_ID, NAME FROM ANIMAL_INS
WHERE INTAKE_CONDITION = 'Sick'
ORDER BY ANIMAL_ID;    # Q3


SELECT ANIMAL_ID, NAME FROM ANIMAL_INS
WHERE INTAKE_CONDITION != 'Aged'
ORDER BY ANIMAL_ID;    # Q4


SELECT ANIMAL_ID, NAME FROM ANIMAL_INS
GROUP BY ANIMAL_ID;   # Q5


SELECT ANIMAL_ID, NAME, DATETIME FROM ANIMAL_INS
ORDER BY NAME, DATETIME DESC;   # Q6


SELECT NAME FROM ANIMAL_INS
ORDER BY DATETIME
LIMIT 1;   # Q7